### ISSUE TITLE
Fix formatting script

### ISSUE THREAD

**Issue by Witek902** [nfprojects/nfengine#23] opened 2014-08-15 19:20 UTC
- Formatting script (format.bat) does not work well for SceneManager.h - for example "Camera\* pCamera" is turned into "Camera \* pCamera".
- Namespaces structure should be indented in Prerequisites.h to improve readability.

**Comment by lookeypl** [comment] 2014-10-18 21:43
Additional issues:
- Missing support for *.hpp files
- Scripts avoid entire nfCommon and nfCommonTest directory
- Scripts work only when launched from Scripts directory

**Comment by lookeypl** [comment] 2014-11-17 20:11
SceneManager.h error is caused by using NFE_ALIGNED_CLASS macro. I tried to fix it, however with no luck. I guess this must be left now as it is, I'll report a bug to astyle Sourceforge.

**Comment by lookeypl** [comment] 2014-11-17 20:27
https://review.gerrithub.io/12381
https://review.gerrithub.io/12382

**Comment by lookeypl** [comment] 2014-11-21 14:10
Merged, closing.

**Closed as completed by lookeypl** 2014-11-21 14:10 UTC
Labels: bug, high priority, small
